//
// Created by Maikol Guzman  on 2019-08-08.
//

#ifndef CALCULOPRESTAMO_CALCULOPRESTAMO_H
#define CALCULOPRESTAMO_CALCULOPRESTAMO_H


class CalculoPrestamo {

};


#endif //CALCULOPRESTAMO_CALCULOPRESTAMO_H
