//
// Created by Maikol Guzman  on 2019-08-05.
//

#ifndef LIBROCALIFICACIONES_LIBROCALIFICACIONES_H
#define LIBROCALIFICACIONES_LIBROCALIFICACIONES_H


class LibroCalificaciones {

};


#endif //LIBROCALIFICACIONES_LIBROCALIFICACIONES_H
